version: 2
jobs:
  build:
    docker:
      - image: docker:git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Create Docker container for volume mounting
          command: |
            docker create --name input --volume /etc/apk/keys --volume /home/builder/package alpine /bin/true
            docker create --name output --volume /packages alpine /bin/true
      - run:
          name: Download public signing key
          command: wget -P /tmp https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub
      - run:
          name: Copy build files into container
          command: |
            docker cp /tmp/sgerrand.rsa.pub input:/etc/apk/keys/sgerrand.rsa.pub
            docker cp ./APKBUILD input:/home/builder/package/APKBUILD
      - run:
          name: Build packages
          command: |
            docker run --env RSA_PRIVATE_KEY="$RSA_PRIVATE_KEY" --env RSA_PRIVATE_KEY_NAME="sgerrand.rsa" \
                       --volumes-from input --volumes-from output sgerrand/alpine-abuild
      - run:
          name: Extract packages
          command: |
            mkdir -p packages
            docker cp output:/packages/builder packages/
      - run:
          name: Test installing packages
          command: |
            wget -P /etc/apk/keys/ https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub
            apk add --no-progress --update-cache --upgrade ./packages/builder/x86_64/leiningen-*.apk
      - run:
          name: Test executable
          command: lein version | grep -q 'Leiningen 2.9.8'
      - run:
          name: Remove Docker volumes
          command: |
            docker rm input
            docker rm output
          when: always
      - store_artifacts:
          destination: pkgs
          path: packages
      - persist_to_workspace:
          root: .
          paths:
            - packages
    working_directory: ~/alpine-pkg-leiningen
  release-main:
    docker:
      - image: golang:alpine
    steps:
      - attach_workspace:
          at: .
      - run: apk add --no-cache --no-progress git
      - run: go install github.com/tcnksm/ghr@latest
      - run:
          name: Release packages
          command: |
            ghr -u sgerrand -r $CIRCLE_PROJECT_REPONAME -prerelease -delete unreleased packages
            ghr -u sgerrand -r $CIRCLE_PROJECT_REPONAME -prerelease unreleased packages/builder/x86_64
    working_directory: ~/alpine-pkg-leiningen
  release-tag:
    docker:
      - image: golang:alpine
    steps:
      - attach_workspace:
          at: .
      - run: apk add --no-cache --no-progress git
      - run: go install github.com/tcnksm/ghr@latest
      - run:
          name: Release packages
          command: |
            ghr -u sgerrand -r $CIRCLE_PROJECT_REPONAME $CIRCLE_TAG packages
            ghr -u sgerrand -r $CIRCLE_PROJECT_REPONAME $CIRCLE_TAG packages/builder/x86_64
    working_directory: ~/alpine-pkg-leiningen
workflows:
  version: 2
  build-test-release:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - release-main:
          requires:
            - build
          filters:
            branches:
              only: main
            tags:
              ignore: /.*/
      - release-tag:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^[0-9]+(\.[0-9]+){1,2}(\-r\d+)?$/
